spring.application.name=demo

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/MaBD
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8001


spring.datasource.url=jdbc:postgresql://dpg-d4j9nkur433s73981t2g-a
spring.datasource.username=springdb_2e0s_user
spring.datasource.password=5S4YaA94fTvi2VEFRIubkU9r0VHDsCnW
spring.jpa.hibernate.ddl-auto=update



